[phases.setup]
nixPkgs = ["ffmpeg", "nodejs"]
aptPkgs = ["ffmpeg", "nodejs"]

[phases.install]
cmds = ["pip install --no-cache-dir -U -r requirements.txt"]

[start]
cmd = "gunicorn --timeout 300 app:app"
